config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/bands', to: 'bands#index'

  get '/bands/new', to: 'bands#new'

  post '/bands', to: 'bands#create'

  get '/bands/:id', to: 'bands#show'

  get '/bands/:id/edit', to: 'bands#edit'

  put '/bands/:id', to: 'bands#update'

  delete '/bands/:id', to: 'bands#delete'

  resources :bands do
    resources :instruments
  end

  get '/colors', to: 'colors#index'

  get '/colors/new', to: 'colors#new'

  post '/colors', to: 'colors#create'

  get '/colors/:id', to: 'colors#show'

  get '/colors/:id/edit', to: 'colors#edit'

  put '/colors/:id', to: 'colors#update'

  delete '/colors/:id', to: 'colors#delete'

  resources :wines

  resources :cars
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :instruments
end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, :model, :year, presence: { if: :required?, message: 'is required.' }

  private

  def required?
    true
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
  validates :name, :presence => {:message => "A color is required"}
  validates :spectrum, :presence => {:message => "A spectrum is required"}
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  belongs_to :band
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  validates :name, :style, :presence => true
  validates :rating, :inclusion => {:in => 0..100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def new
  end

  def create
    band = Band.new
    band.name = params[:name]
    band.genre = params[:genre]
    band.members = params[:members]
    band.save
    redirect_to '/bands'
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    band = Band.find(params[:id])
    band.update_attributes(:name => params[:name], :genre => params[:genre], :members => params[:members])
    redirect_to '/bands'
  end

  def delete
    band = Band.find(params[:id])
    band.destroy
    redirect_to '/bands'
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @car = Car.new
  end

  def create
    car = Car.new(allowed_parameters)
    if car.save
      redirect_to cars_path
    else
      @car = car
      render :new
    end
  end

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    car = Car.find(params[:id])
    if car.update(allowed_parameters)
      redirect_to cars_path
    else
      @car = car
      render :edit
    end
  end

  private

  def allowed_parameters
    params.require(:car).permit(:model, :make, :year, :engine, :turbocharged)
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
    @colors = Color.all
  end

  def new
    @color = Color.new
  end

  def create
    @color = Color.new
    @color.name = params[:name]
    @color.primary = params[:primary]
    @color.spectrum = params[:spectrum]

    if @color.save
      redirect_to '/colors', notice: "Color successfully added"
    else
      render :new
    end
  end

  def show
    @color = Color.find(params[:id])
  end

  def edit
    @color = Color.find(params[:id])
  end

  def update
    @color = Color.find(params[:id])
    @color.update(:name => params[:name], :primary => params[:primary], :spectrum => params[:spectrum])

    if @color.save
      redirect_to '/colors', notice: "Color successfully updated"
    else
      render :edit
    end
  end

  def delete
    @color = Color.find(params[:id])
    @color.destroy
    redirect_to '/colors', notice: "Color successfully deleted"
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    @instruments = Instrument.where(band_id: params[:band_id])
  end

  def new
    @instrument = Instrument.new
    @choices = ['Acoustic Guitar', 'Electric Guitar', 'Bass', 'Drums', 'Slide Guitar', 'Banjo', 'Mandolin', 'Dobro', 'Fiddle']
  end

  def create
    instrument = Instrument.new(allowed_parameters.merge(band_id: params[:band_id]))
    if instrument.save
      redirect_to band_instruments_path
    else
      @instrument = instrument
      render :new
    end
  end

  private

  def allowed_parameters
    params.require(:instrument).permit(:kind, :manufacturer, :model, :year, :color)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def index
    @wines = Wine.all
  end

  def new
    @wine = Wine.new
  end

  def create
    wine = Wine.new
    wine.name = params[:wine][:name]
    wine.style = params[:wine][:style]
    wine.color = params[:wine][:color]
    wine.rating = params[:wine][:rating]
    if wine.save
      redirect_to :wines
    else
      @wine = wine
      render :new
    end
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  def update
    wine = Wine.find(params[:id])
    wine.name = params[:wine][:name]
    wine.style = params[:wine][:style]
    wine.color = params[:wine][:color]
    wine.rating = params[:wine][:rating]
    if wine.save
      redirect_to wines_path
    else
      @wine = wine
      render :edit
    end
  end

  def destroy
    wine = Wine.find(params[:id])
    wine.destroy
    redirect_to '/wines'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/bands/edit.html.haml
%form{:action => "/bands/#{@band.id}", :method => 'post'}
  %input{:type => 'hidden', :name => '_method', :value => 'put'}
  %label Band Name
  %input{:type => 'text', :name => 'name', :value => @band.name}
  %label Genre
  %input{:type => "text", :name => "genre", :value => @band.genre}
  %label # of members
  %input{:type => "text", :name => "members", :value => @band.members}
  %button{:type => "submit", :value => "Update Band"} Update Band

%form{:action => "/bands/#{@band.id}", :method => 'post'}
  %input{:type => 'hidden', :name => '_method', :value => 'delete'}
  %button{:type => 'submit', :value => "Delete"} Delete

app/views/bands/index.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Bands
  %nav
    %div{:id => 'nav_container'}
      %ul{:id => 'menu'}
        %li
          %a{:href => '/bands/new'}Create

%div{:id => 'content_container'}
  %table{:class => 'dataset'}
    %tr
      %td Name
      %td Genre
      %td Number of Members
    - @bands.each do |band|
      %tr
        %td
          %a{:href => "/bands/#{band.id}"}=band.name
        %td
          %a{:href => "/bands/#{band.id}"}= band.genre
        %td
          %a{:href => "/bands/#{band.id}"}= band.members

app/views/bands/new.html.haml
%form{:action => "/bands", :method => 'post'}
  %label Band Name
  %input{:type => "text", :name => "name"}
  %label Genre
  %input{:type => "text", :name => "genre"}
  %label # of members
  %input{:type => "text", :name => "members"}
  %button{:type => "submit", :value => "Create Band"}Create Band

app/views/bands/show.html.haml
= @band.name
= @band.genre
= @band.members
= link_to 'Instruments', band_instruments_path(@band)

%a{:href => "/bands/#{@band.id}/edit"}Edit

app/views/cars/_cars.html.haml
- @cars.each do |car|
  %tr
    %td= link_to car.make, car_path(car.id)
    %td= car.model
    %td= car.year
    %td= car.engine
    %td= car.turbocharged.to_s.capitalize

app/views/cars/_form.html.haml
#form_container
  - if @car.errors.present?
    .error_list
      - @car.errors.full_messages.each do |error|
        %li= error
  = form_for @car do |f|
    .form-input
      = f.label :make
      = f.text_field :make
    .form-input
      = f.label :model
      = f.text_field :model
    .form-input
      = f.label :year
      = f.number_field :year
    .form-input
      = f.label :engine
      = f.select(:engine, %w(4-cylinder V6 V8 V10 V12 Rotary), include_blank: true)
    .form-input
      = f.label :turbocharged
      = f.check_box(:turbocharged)
    .form-submit
      = f.submit

app/views/cars/edit.html.haml
#content_container
  %h1 Edit Car

  = render 'form'

app/views/cars/index.html.haml
#header_container
  %header
    %h1
      Cars

#content_container
  %table.dataset
    %tr
      %td
        Make
      %td
        Model
      %td
        Year
      %td
        Engine
      %td
        Turbocharged
    = render 'cars'
  = link_to 'Add Car', new_car_path

app/views/cars/new.html.haml
#content_container
  %h1 Add Car

  #form_container
    = @car.errors.full_messages.each do |error|
      = error
    = form_for @car do |f|
      .form-input
        = f.label :make
        = f.text_field :make
      .form-input
        = f.label :model
        = f.text_field :model
      .form-input
        = f.label :year
        = f.number_field :year
      .form-input
        = f.label :engine
        = f.select(:engine, %w(4-cylinder V6 V8 V10 V12 Rotary), include_blank: true)
      .form-input
        = f.label :turbocharged
        = f.check_box(:turbocharged)
      .form-submit
        = f.submit "Add"

app/views/cars/show.html.haml
#content_container
  %ul
    %li= @car.make
    %li= @car.model
    %li= @car.year
    %li= @car.engine
    %li= @car.turbocharged

  = link_to 'Edit', edit_car_path

app/views/colors/edit.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Edit Color

%div{:id => 'form_container'}
  %form{:action => "/colors/#{@color.id}", :method => 'post'}
    %input{:name => "_method", :type => "hidden", :value => "put"}
    %input{:name => "authenticity_token", :type => "hidden", :value => "#{form_authenticity_token}"}
    - if @color.errors.present?
      %div{:class => 'error_list'}
        - @color.errors.each do |_, message|
          %li
            = message
    %label Name
    %input{:type => 'text', :name => 'name', :value => @color.name}
    %label Primary?
    %input{:type => 'checkbox', :name => 'primary', :value => @color.primary}
    %label Spectrum
    %input{:type => 'text', :select => 'yes', :name => 'spectrum', :value => @color.spectrum}
    %button{:type => 'submit', :value => 'add color'} Update Color

= button_to 'Delete', { action: "delete", id: @color.id }, method: :delete

app/views/colors/index.html.haml
- if flash
  - flash.each do |_, message|
    %p
      = message

%div{:id => 'header_container'}
  %header
    %h1 Colors
    %a{:href => '/colors/new'}Add Color

%div{:id => 'content_container'}
  %table{:class => 'dataset'}
    %tr
      %td Name
      %td Primary?
      %td Spectrum
    - @colors.each do |color|
      %tr
        %td
          %a{:href => "/colors/#{color.id}"}
            = color.name
        %td
          = (color.primary).to_s.capitalize
          = "False" unless color.primary
        %td
          = color.spectrum
          Spectrum

app/views/colors/new.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Add Color

%div{:id => 'form_container'}
  %form{:action => '/colors', :method => 'post'}
    %input{:name => "authenticity_token", :type => "hidden", :value => "#{form_authenticity_token}"}
    - if @color.errors.present?
      %div{:class => 'error_list'}
        - @color.errors.each do |_, message|
          %li
            = message
    %label Name
    %input{:type => 'text', :name => 'name'}
    %label Primary?
    %input{:type => 'checkbox', :name => 'primary'}
    %label Spectrum
    %input{:type => 'text', :select => 'yes', :name => 'spectrum'}
    %button{:type => 'submit', :value => 'add color'} Add Color

app/views/colors/show.html.haml
%ul
  %li
    Name:
    = @color.name
  %li
    Primary color?
    = @color.primary.to_s.capitalize
  %li
    Spectrum:
    = @color.spectrum
    Spectrum

%a{:href => "/colors/#{@color.id}/edit"} Edit

app/views/instruments/index.html.haml
#header_container
  %header
    %h1
      Instruments

#content_container
  %table.dataset
    %tr
      %td
        Kind
      %td
        Manufacturer
      %td
        Model
      %td
        Year
      %td
        Color
    - if @instruments.present?
      - @instruments.each do |instrument|
        %tr
          %td
            = instrument.kind
          %td
            = instrument.manufacturer
          %td
            = instrument.model
          %td
            = instrument.year
          %td
            = instrument.color

  = link_to 'Add Instrument', new_band_instrument_path

app/views/instruments/new.html.haml
= form_for @instrument, url: {action: "create"} do |f|
  = f.label :kind
  = f.select :kind, @choices
  = f.label :manufacturer
  = f.text_field :manufacturer
  = f.label :model
  = f.text_field :model
  = f.label :year
  = f.date_select :year, :start_year => 1900, :discard_month => true, :discard_day => true
  = f.label :color
  = f.text_field :color
  = f.submit 'Add Instrument'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content_container">
  <%= yield %>
</div>
</body>
</html>

app/views/welcome/index.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Rails CRUD

%div{:id => 'content_container'}
  %ul
    %li
      %a{:href => '/bands'}Bands
      \- Basic CRUD with Nested Routes (Instruments)
    %li
      %a{:href => '/colors'}Colors
      \- Basic CRUD with Validations
    %li
      %a{:href => '/wines'}Wines
      \- Validations, helpers, and unit testing
    %li
      = link_to 'Cars', cars_path
      \- Link_to, custom errors, and partials

app/views/wines/edit.html.haml
#form_container
  = form_for @wine do |f|
    - if @wine.errors.present?
      .error_list
        - @wine.errors.full_messages.each do |message|
          = message
          %br
    .form-input
      = f.label :name
      = f.text_field(:name)
    .form-input
      = f.label :style
      = f.text_field(:style)
    .form-input
      = f.label :color
      = f.text_field(:color)
    .form-input
      = f.label :rating
      = f.text_field(:rating)
    .form-submit
      = f.submit 'Update'
%br
#form_container
  =button_to "Delete", "/wines/#{@wine.id}", id: @wine.id, method: 'delete'

app/views/wines/index.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Wines
    =link_to('New wine', :new_wine)

%div{:id => 'content_container'}
  %table{:class => 'dataset'}
    %tr
      %td
        Name
      %td
        Style
      %td
        Color
      %td
        Rating
    -@wines.each do |wine|
      %tr
        %td
          =link_to(wine.name, wine_path(wine))
        %td
          =wine.style
        %td
          =wine.color
        %td
          =wine.rating

app/views/wines/new.html.haml
%div{:id => 'header_container'}
  %header
    %h1 Add Wine

%div{:id => 'form_container'}
  =form_for(@wine) do |f|
    -if @wine.errors.any?
      %div{:class => 'error_list'}
        -@wine.errors.full_messages.each do |message|
          =message
          %br
    .form-input
      =f.label('Name')
      =f.text_field(:name)
    .form-input
      =f.label('Style')
      =f.text_field(:style)
    .form-input
      =f.label('Color')
      =f.text_field(:color)
    .form-input
      =f.label('Rating')
      =f.text_field(:rating)
    .form-submit
      =f.submit('Create')

app/views/wines/show.html.haml
%ul
  %li
    Name:
    = @wine.name
  %li
    Style:
    = @wine.style
  %li
    Color:
    = @wine.color
  %li
    Rating:
    = @wine.rating

=link_to("Edit", edit_wine_path)
=link_to("Back", wines_path)